SET SERVEROUTPUT ON;

CREATE TABLE S_DEPT
(
    ID NUMBER(7)CONSTRAINT S_DEPT_PK PRIMARY KEY
)

CREATE TABLE S_EMP
(
    ID NUMBER(7)CONSTRAINT S_EMP_PK PRIMARY KEY,
    LAST_NAME VARCHAR(30),
    FIRST_NAME VARCHAR(30),
    USERID NUMBER(7),
    START_DATE DATE,
    SALARY NUMBER
)

CREATE TABLE S_CUSTOMER
(
    ID NUMBER(7)CONSTRAINT S_CUSTOMER_PK PRIMARY KEY,
    NAME VARCHAR(30)
)

CREATE TABLE S_WAREHOUSE
(
    ID NUMBER(7)CONSTRAINT S_WAREHOUSE_PK PRIMARY KEY,
    MANAGER_ID NUMBER(7),
    CONSTRAINT S_WAREHOUSE_MANAGER_ID_FK FOREIGN KEY(MANAGER_ID) REFERENCES S_EMP(ID)
)


CREATE TABLE S_ORD
(
    ID NUMBER(7)CONSTRAINT S_ORD_PK PRIMARY KEY,
    CUSTOMER_ID NUMBER(7),
    CONSTRAINT S_ORD_CUSTOMER_ID_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES S_CUSTOMER(ID)
)

CREATE TABLE S_PRODUCT
(
    ID NUMBER(7)CONSTRAINT S_PRODUCT_PK PRIMARY KEY
)
CREATE TABLE S_ITEM
(
    ORD_ID NUMBER(7),
    PRODUCT_ID NUMBER(7),
    PRICE NUMBER,
    QUANTITY NUMBER,
    CONSTRAINT S_ITEM_PK PRIMARY KEY(ORD_ID, PRODUCT_ID),
    CONSTRAINT S_ITEM_ORD_ID_FK FOREIGN KEY(ORD_ID) REFERENCES S_ORD(ID),
    CONSTRAINT S_ITEM_PRODUCT_ID_FK FOREIGN KEY(PRODUCT_ID) REFERENCES S_PRODUCT(ID)
)

INSERT INTO S_EMP VALUES(1, 'Nhan vien', 'A', 1, TO_DATE('1/1/1979', 'dd/MM/yyyy'), 1);
INSERT INTO S_EMP VALUES(2, 'Nhan vien', 'B', 2, TO_DATE('1/1/1989', 'dd/MM/yyyy'), 2);
INSERT INTO S_EMP VALUES(3, 'Nhan vien', 'C', 3, TO_DATE('1/2/1988', 'dd/MM/yyyy'), 3);
INSERT INTO S_EMP VALUES(5, 'Nhan vien', 'D', 4, TO_DATE('1/2/1989', 'dd/MM/yyyy'), 3000000);

INSERT INTO S_WAREHOUSE VALUES(1, 1);
INSERT INTO S_WAREHOUSE VALUES(2, 1);
INSERT INTO S_WAREHOUSE VALUES(3, 1);
INSERT INTO S_WAREHOUSE VALUES(4, 2);
INSERT INTO S_WAREHOUSE VALUES(6, 3);

CREATE OR REPLACE TRIGGER TRG_CAUB
BEFORE INSERT OR UPDATE OF MANAGER_ID ON S_WAREHOUSE
FOR EACH ROW
DECLARE
    PRAGMA AUTONOMOUS_TRANSACTION;
    V_NUM_WH NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_NUM_WH
    FROM S_WAREHOUSE
    WHERE MANAGER_ID = :NEW.MANAGER_ID;
    
    IF(V_NUM_WH >=3)
    THEN
        RAISE_APPLICATION_ERROR(-20010, 'Nhan vien khong duoc quan ly qua 3 nha kho');
    END IF;
END;
--Check
INSERT INTO S_WAREHOUSE VALUES(5, 1);
UPDATE S_WAREHOUSE
SET MANAGER_ID = 1
WHERE ID = 4;

DECLARE 
    CURSOR EMP_CUR
    IS
        SELECT LAST_NAME, FIRST_NAME,START_DATE, SALARY
        FROM S_EMP
        WHERE SALARY > 15000
        AND START_DATE > TO_DATE('1/2/1988','dd/MM/yyyy');
BEGIN
    FOR R_EMP IN EMP_CUR
    LOOP
        DBMS_OUTPUT.PUT_LINE(R_EMP.LAST_NAME);
    END LOOP;
END;


